---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: secure-maprfs-sdc
   namespace: streamsets
provisioner: mapr.com/maprfs
parameters:
    restServers: "apiserver0:8443 apiserver1:8443 apiserver2:8443"
    cldbHosts: "cldb0 cldb1 cldb2"
    cluster: "cluster_name_here"
    securityType: "secure"
    ticketSecretName: "sdc-ticket-secret"
    ticketSecretNamespace: "streamsets"
    maprSecretName: "sdc-secrets"
    maprSecretNamespace: "streamsets"
    namePrefix: "ss"
    mountPrefix: "/pv"
    advisoryquota: "1G" 
    reclaimPolicy: "Retain"
    type: "rw"
    mount: "1"
  
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
  namespace: streamsets
  labels:
    app: datacollector
spec:
  ports:
  - port: 18630
    targetPort: 18630
    name: ui
#  clusterIP: None
  selector:
    app: datacollector
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: datacollector
  namespace: streamsets
spec:
  serviceName: "datacollector"
  replicas: 1
  template:
    metadata:
      labels:
        app: datacollector
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-datacollector-data",
            "image": "busybox",
            "command": ["sh", "-c", "chown -R 20159 /data /opt/streamsets-datacollector/streamsets-libs"],
            "volumeMounts": [
              {"name": "data", "mountPath": "/data", "subPath": "data"},
              {"name": "data", "mountPath": "/opt/streamsets-datacollector/streamsets-libs", "subPath": "stagelibs"}
            ]
          }
        ]'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: datacollector
        image: streamsets/datacollector
        ports:
        - containerPort: 18630
          name: ui
        readinessProbe:
          exec:
            command: ["curl", "127.0.0.1:18630/public-rest/ping"]
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        - name: data
          mountPath: /opt/streamsets-datacollector/streamsets-libs
          subPath: stagelibs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2G
      storageClassName: secure-maprfs-sdc
